baseurl = "https://www.investingrus.com/"
title = "The Investing for the Rest of Us"
languageCode = "en-us"
pygmentsuseclasses = true
googleAnalytics = "UA-XXXXXXXX-XX" # tracking through cloudflare
disqusShortname = "investingrus"

[Params]
  Author = "Sergey Kolos"